version: '3.8'

services:
  letsplay-psql:
    container_name: letsplay-psql
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: letsplay
      POSTGRES_USER: letsplay
      POSTGRES_PASSWORD: letsplay@2023
    volumes:
      - letsplay-data:/var/lib/postgresql/data
    restart: always

volumes:
  letsplay-data:
