export enum MusicStylesEnum {
    heavy = "Heavy Metal",
    thrash = "Thrash Metal",
    death = "Death Metal",
    black = "Black Metal",
    power = "Power Metal",
    prog = "Prog",
    doom = "Doom",
    symphonic = "Symphonique",
    folk = "Folk",
    indus = "Indus",
    melodic = "Mélodique",
    nu = "Neo",
    alternative = "Alternatif",
    core = "Metalcore",
    grind = "Grindcore",
    stoner = "Stoner",
    post = "Post Metal",
    djent = "Djent"
}
