name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Adding secrets to application.properties
        run: |
          echo "Setting application.properties for prod build"
          echo "spring.datasource.url=${{ secrets.DB_URL }}" >> ./letsplay-backend/src/main/resources/application-prod.properties
          echo "spring.datasource.username=${{ secrets.DB_USER }}" >> ./letsplay-backend/src/main/resources/application-prod.properties
          echo "spring.datasource.password=${{ secrets.DB_PASSWORD }}" >> ./letsplay-backend/src/main/resources/application-prod.properties
          echo "Here's the updated file:"
          cat ./letsplay-backend/src/main/resources/application-prod.properties
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push back-end
        run: |
          cd letsplay-backend/
          echo "Building back-end image"
          ls -a
          docker build -f Dockerfile . -t ${{ secrets.DOCKERHUB_USERNAME }}/letsplay-backend:latest  --progress=plain
          echo "Pushing back-end image"
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/letsplay-backend:latest

      - name: Build and push front-end
        run: |
          cd letsplay-frontend/
          echo "Building front-end image"
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/letsplay-frontend:latest .
          echo "Pushing front-end image"
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/letsplay-frontend:latest
