name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Adding secrets to application.properties
        run: |
          echo "spring.datasource.url=${{ secrets.DB_URL }}" >> ./letsplay-backend/src/main/resources/application-prod.properties
          echo "spring.datasource.username=${{ secrets.DB_USERNAME }}" >> ./letsplay-backend/src/main/resources/application-prod.properties
          echo "spring.datasource.password=${{ secrets.DB_PASSWORD }}" >> ./letsplay-backend/src/main/resources/application-prod.properties
          cat ./letsplay-backend/src/main/resources/application-prod.properties
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - 
        name: Build and push Docker backend image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./letsplay-backend/
          file: ./letsplay-backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/letsplay-backend:latest

      - name: Build and push Docker frontend image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./letsplay-frontend/
          file: ./letsplay-backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/letsplay-backend:latest

