name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      #- 
       # name: Build and push back-end
        #run: |
         # cd letsplay-backend/letsplay/
          #echo "Building back-end image"
          #docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/letsplay-backend:latest .
          #echo "Pushing back-end image"
          #docker push ${{ secrets.DOCKERHUB_USERNAME }}/letsplay-backend:latest

      - name: Build and push front-end
        run: |
          cd letsplay-frontend/
          echo "Building front-end image"
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/letsplay-frontend:latest .
          echo "Pushing front-end image"
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/letsplay-frontend:latest
